In [36]:
import pandas as pd
data = pd.read_csv('wineq.csv', delimiter=';')
data.head()

fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  Output
0            7.0              0.27         0.36  ...      8.8        6       1
1            6.3              0.30         0.34  ...      9.5        6       1
2            8.1              0.28         0.40  ...     10.1        6       1
3            7.2              0.23         0.32  ...      9.9        6       1
4            7.2              0.23         0.32  ...      9.9        6       1

[5 rows x 13 columns]

In [37]:

import numpy as np
# Use np.loadtxt() instead when there are non-numeric values as well
dataset = np.genfromtxt('wineq.csv', delimiter=";", skip_header = True)
dataset

array([[ 7.0,  0.3,  0.4, ...,  8.8,  6.0,  1.0],
       [ 6.3,  0.3,  0.3, ...,  9.5,  6.0,  1.0],
       [ 8.1,  0.3,  0.4, ...,  10.1,  6.0,  1.0],
       ...,
       [ 6.5,  0.2,  0.2, ...,  9.4,  6.0,  1.0],
       [ 5.5,  0.3,  0.3, ...,  12.8,  7.0,  1.0],
       [ 6.0,  0.2,  0.4, ...,  11.8,  6.0,  1.0]])

In [38]:

np.set_printoptions(precision = 2) # does not work for too wide array
np.set_printoptions(formatter = {'float': '{: 0.1f}'.format})

print('')
print(dataset.shape)
print('')
print(dataset[0:5])


(4898, 13)

[[ 7.0  0.3  0.4  20.7  0.0  45.0  170.0  1.0  3.0  0.5  8.8  6.0  1.0]
 [ 6.3  0.3  0.3  1.6  0.0  14.0  132.0  1.0  3.3  0.5  9.5  6.0  1.0]
 [ 8.1  0.3  0.4  6.9  0.1  30.0  97.0  1.0  3.3  0.4  10.1  6.0  1.0]
 [ 7.2  0.2  0.3  8.5  0.1  47.0  186.0  1.0  3.2  0.4  9.9  6.0  1.0]
 [ 7.2  0.2  0.3  8.5  0.1  47.0  186.0  1.0  3.2  0.4  9.9  6.0  1.0]]


In [39]:
X = dataset[:, :-2]
Y = dataset[:, -1]


array([ 1.0,  1.0,  1.0, ...,  1.0,  1.0,  1.0])

In [44]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(1, input_dim = len(X[0, :]),)) #activation='sigmoid'#))

In [45]:
model.compile(loss='binary_crossentropy', optimizer = 'rmsprop', metrics=['accuracy'])
model.fit(X, Y, epochs = 256, verbose = 1)

Epoch 1/256
154/154 [==============================] - 1s 1ms/step - loss: nan - accuracy: 0.3348
Epoch 2/256
154/154 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.3348
Epoch 3/256
154/154 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.3348
Epoch 4/256
154/154 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.3348
Epoch 5/256
154/154 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.3348
Epoch 6/256
154/154 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.3348
Epoch 7/256
154/154 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.3348
Epoch 8/256
154/154 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.3348
Epoch 9/256
154/154 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.3348
Epoch 10/256
154/154 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.3348
Epoch 11/256
154/15

KeyboardInterrupt: ignored

In [43]:
print ('True Validation Data:')
print(Y[:10])
prediction = model.predict(X)
print ('Prediction:')
print(prediction[0:10].T)

True Validation Data:
[ 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0]
Prediction:
[[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]]
