In [7]:
##############################################################################################################################################################
##############################################################################################################################################################
###### Python Predictor                                                                                                                                 ######
###### Version: 1.3                                                                                                                                     ######
###### In this pirticular model, Logistical regression is used for binary classification                                                                ######
###### Author: Group                                                                                                                                    ######
##############################################################################################################################################################
##############################################################################################################################################################


# Importing Data (White wine qualtity)
import pandas as pd
data = pd.read_csv('wwine.csv', delimiter=',') #storing imprted data in attributies.
data.head() # Just checking how are first few columns of data, making sure that the output values are indeed Binary. 

# manupulating the data so that if there are non numeric values, text can be loaded like numbers as well. 
import numpy as np
dataset = np.genfromtxt('wwine.csv', delimiter=",", skip_header = True)
dataset # checking again whether dataset is correctly manipulated.

# setting the prescion to upto 2 values and then rounding it off.
np.set_printoptions(precision = 2) # does not work for too wide array
np.set_printoptions(formatter = {'float': '{: 0.1f}'.format})

# Data Check
print('')
print(dataset.shape)
print('')
print(dataset[0:5])

# Spliting the data into intput and output
X = dataset[:, :-2] #Input all colums except the outcome and qualty (on which the outcome is based)
Y = dataset[:, -1] # Outcome Column

# Splititng the data again into training data and testing data.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size= 0.7)



(1599, 13)

[[ 7.4  0.7  0.0  1.9  0.1  11.0  34.0  1.0  3.5  0.6  9.4  5.0  0.0]
 [ 7.8  0.9  0.0  2.6  0.1  25.0  67.0  1.0  3.2  0.7  9.8  5.0  0.0]
 [ 7.8  0.8  0.0  2.3  0.1  15.0  54.0  1.0  3.3  0.7  9.8  5.0  0.0]
 [ 11.2  0.3  0.6  1.9  0.1  17.0  60.0  1.0  3.2  0.6  9.8  6.0  1.0]
 [ 7.4  0.7  0.0  1.9  0.1  11.0  34.0  1.0  3.5  0.6  9.4  5.0  0.0]]


In [8]:
# Using tenserflow / keras to bulid the model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(1, input_dim = len(X_train[0, :]),activation='sigmoid'))  
# instead of sigmoid, we can also use linear, for linear regression, but i think it makes more sense to use sigmoid because of the fact that the data is binarry classification data.




In [11]:
# loss mattrix is binary cause we have our outputs as 1,0. 
# Choosing rms as optimiser and metrics as accuracy.
# metrics depends on the output.

model.compile(loss='binary_crossentropy', optimizer = 'rmsprop', metrics=['accuracy'])
model.fit(X_train, y_train, epochs = 512, verbose = 1)


Epoch 1/512
15/15 [==============================] - 0s 1ms/step - loss: 0.5363 - accuracy: 0.7328
Epoch 2/512
15/15 [==============================] - 0s 2ms/step - loss: 0.5369 - accuracy: 0.7411
Epoch 3/512
15/15 [==============================] - 0s 2ms/step - loss: 0.5361 - accuracy: 0.7307
Epoch 4/512
15/15 [==============================] - 0s 2ms/step - loss: 0.5365 - accuracy: 0.7307
Epoch 5/512
15/15 [==============================] - 0s 1ms/step - loss: 0.5359 - accuracy: 0.7370
Epoch 6/512
15/15 [==============================] - 0s 1ms/step - loss: 0.5370 - accuracy: 0.7411
Epoch 7/512
15/15 [==============================] - 0s 1ms/step - loss: 0.5358 - accuracy: 0.7537
Epoch 8/512
15/15 [==============================] - 0s 1ms/step - loss: 0.5403 - accuracy: 0.7328
Epoch 9/512
15/15 [==============================] - 0s 2ms/step - loss: 0.5361 - accuracy: 0.7453
Epoch 10/512
15/15 [==============================] - 0s 1ms/step - loss: 0.5362 - accuracy: 0.7411
Epoch 11/

In [12]:
# checking the validation and prediction , in this irticular case, its based on accuracy
print ('True Validation Data:')
print(y_test[:10])
prediction = model.predict(X_test)
print ('Prediction:')
print(prediction[0:10].T) 

True Validation Data:
[ 1.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0]
Prediction:
[[ 1.0  0.4  0.7  0.8  0.8  0.6  0.2  0.7  0.2  0.2]]
